### ISSUE TITLE
While Parler is down...

### ISSUE THREAD

**Issue by TAbdiukov** [sickcodes/security#2]
You were one of the coolest guys there I followed, so we might as well create a thread substituting Parler for (hopefully!) a couple of days - maybe others will find the temporary 'camp' of ours

------------------------------------------------
I wanted to add my 2c re:Parler app for iOS

I know AltStore is probably the most optimal solution (albeit the most complicated one, and probably the one that voids warranty), but if we acquire the last AppStore Parler release for iOS, which [happens to be Parler v3.28 from December 10, 2020](https://www.ipa4fun.com/ipa/325424/) ([archived link @ IA](https://web.archive.org/web/20210111040720/https://www.ipa4fun.com/ipa/325424/))

Now this version will be ever-outdating, but if we acquire this .IPA, it will be signed by Apple Inc themselves - which means one could install that .IPA directly with [the older version of iTunes](https://osxdaily.com/2017/10/09/get-itunes-12-6-3-with-app-store/). And while iTunes is br0ken (especially that version), iOS still supports app installations with this method

Side thoughts: if we get the private key of Apple that is used for signing apps, it's all over for locked-in apps :joy:

**Comment by TAbdiukov** [comment]
Parler IPAs FOUND: https://github.com/pricemi115/parler
iTunes link (dead): itms://itunes.apple.com/app/id1402727988?mt=8

**Comment by sickcodes** [comment]
Hey there! I tested altstore and it's a pain in the ass to fully setup the app. It also wasn't working on open. It will probably wind up back on the store according to Tim Cook.
